on: [workflow_dispatch]
 
jobs:
  run-ispw-deploy:
    runs-on: [self-hosted]
    name: A job to deploy in Code Pipeline
    steps:
      - name: Deploy
        uses: bmc-compuware/ispw-deploy@ZENG-308808-Add-Certificate-Support-For-Deploy-Action
        id: deploy
        with:
          ces_url: "http://localhost:48080/"
          certificate: ${{ secrets.KAJAL_CERTIFICATE }}
          srid: cw09-47624
          runtime_configuration: TPTP
          assignment_id: ISP4000073
          level: DEV1
          task_id: "7E82A9C5EF09"
      - name: Get the set ID for the deploy
        run: echo "The Code Pipeline set used for the deploy is ${{ steps.deploy.outputs.set_id }}"
